import { type NextRequest, NextResponse } from 'next/server'
import { rebuildPdfs, wasRecentlyRebuilt } from '@/lib/pdfRebuilder'
import { getPdfsToRegenerateFromFile } from '@/lib/pdfSectionMapper'
import {
  addSubscriber,
  broadcast,
  getSubscriberCount,
  removeSubscriber,
  sendToController,
} from '@/lib/sseNotifier'

interface ReloadPayload {
  path: string
  type: 'change' | 'add' | 'unlink'
  timestamp: number
}

const REBUILD_DEBOUNCE_MS = 5000

export async function POST(request: NextRequest) {
  try {
    const payload: ReloadPayload = await request.json()

    console.log(`[Reload] Received notification:`, payload)

    const fileName = payload.path.substring(payload.path.lastIndexOf('/') + 1)
    const isMetadataFile = fileName === 'metadata.json'

    if (isMetadataFile) {
      console.log(`[Reload] Skipping PDF rebuild for metadata.json (generated by PDF process)`)
    }

    const directoryPath = payload.path.includes('/')
      ? `resumes/${payload.path.substring(0, payload.path.lastIndexOf('/'))}`
      : 'resumes'

    console.log(`[Reload] Extracted directory path: ${directoryPath}`)

    if (payload.type !== 'unlink' && directoryPath && !isMetadataFile) {
      const recentlyRebuilt = wasRecentlyRebuilt(directoryPath, REBUILD_DEBOUNCE_MS)
      console.log(`[Reload] Rebuild check for ${directoryPath}: recentlyRebuilt=${recentlyRebuilt}`)

      if (recentlyRebuilt) {
        console.log(
          `[Reload] ⏭️  Skipping PDF rebuild for ${directoryPath} (rebuilt within ${REBUILD_DEBOUNCE_MS}ms)`,
        )
      } else {
        const pdfsToRegenerate = getPdfsToRegenerateFromFile(payload.path)

        if (pdfsToRegenerate.length === 0) {
          console.log(`[Reload] ⏭️  File ${payload.path} doesn't affect PDFs, skipping regeneration`)
        } else {
          console.log(`[Reload] ✅ Triggering PDF rebuild for: ${directoryPath} from watcher`)
          console.log(
            `[Reload] 📄 Regenerating: ${pdfsToRegenerate.join(', ')} (based on file: ${payload.path})`,
          )

          rebuildPdfs(directoryPath, pdfsToRegenerate).catch((err) => {
            console.error(`[Reload] PDF rebuild failed:`, err)
          })
        }
      }
    }

    broadcast({ ...payload })

    return NextResponse.json({
      success: true,
      subscribers: getSubscriberCount(),
      payload,
    })
  } catch (error) {
    console.error('[Reload] Error handling reload notification:', error)
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to process reload',
      },
      { status: 500 },
    )
  }
}

export async function GET() {
  const stream = new ReadableStream({
    start(controller) {
      addSubscriber(controller)

      sendToController(controller, `data: ${JSON.stringify({ type: 'connected' })}\n\n`)

      const keepAlive = setInterval(() => {
        try {
          sendToController(controller, `: keepalive\n\n`)
        } catch {
          clearInterval(keepAlive)
          removeSubscriber(controller)
        }
      }, 30000)

      return () => {
        clearInterval(keepAlive)
        removeSubscriber(controller)
      }
    },
  })

  return new NextResponse(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
    },
  })
}
